site_name: Techjam Backend
site_url: https://venture-capitech.github.io/backend

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: README.md
  - Scripts:
    - Getting Started: scripts/getting-started.md
    - Pushing to Github: scripts/push-to-github.md
